In [2]:
import numpy as np
#陣列運算
a = np.array([1,3,5,7,9])
a *= 10
a

array([10, 30, 50, 70, 90])

In [3]:
a = np.array([1,3,5,7,9])
b = np.array([2,4,6,8,10])

#陣列運算
a + b

array([ 3,  7, 11, 15, 19])

In [ ]:
#2維ndarray
arr = np.array([[1, 3, 5],[2, 4, 6]])
arr.ndim #維度
arr.shape #形狀(列,欄)
arr.size #元素數量
arr.dtype #型別

dtype('int64')

In [33]:
np.random.rand()
np.random.rand(5,10)

array([[0.88145079, 0.6708042 , 0.71639566, 0.28115642, 0.20040657,
        0.32246359, 0.25544412, 0.90960801, 0.5913077 , 0.14924393],
       [0.1555992 , 0.35617096, 0.08265123, 0.13436957, 0.37774744,
        0.3464778 , 0.18262859, 0.25354154, 0.25775102, 0.1184442 ],
       [0.3354585 , 0.41845282, 0.93230908, 0.07963692, 0.05251716,
        0.9383271 , 0.83040822, 0.2573278 , 0.08357622, 0.93757674],
       [0.26742136, 0.45978576, 0.74997131, 0.9999423 , 0.95875528,
        0.9822614 , 0.26596853, 0.95285763, 0.81303784, 0.89010567],
       [0.01259796, 0.62715242, 0.77760557, 0.70456573, 0.96527276,
        0.69058739, 0.14839907, 0.14415105, 0.696731  , 0.48711114]])

In [40]:
scores = np.random.randint(0,101,size=(10,5))
scores

array([[ 30,  46,  55,  46,  54],
       [ 17,  36,  18,  45,  22],
       [ 20,  75,  39,  79,  36],
       [ 49,  96,  45,  63,   7],
       [ 58,  86,  12,  14,  46],
       [ 54, 100,  27,  87,  88],
       [ 67,   1,  68,  76,   7],
       [ 77,  68,  38,  89,  94],
       [ 69,  86,   6,  54,  52],
       [ 73,  13,  54,  24,  43]], dtype=int32)