In [1]:
import numpy as np
arr = np.arange(10) * 10
arr

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [2]:
#索引
arr[1]

#slice
arr[:5] #前五個,不含5
arr[-5:] #後5個

array([50, 60, 70, 80, 90])

In [3]:
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 71,  68,  56,  78,  89],
       [ 67,  77,  52,  54,  90],
       [ 57,  65, 100,  90,  57],
       [ 87,  50,  96,  63,  75],
       [ 73,  55,  99,  64,  92],
       [ 93,  76,  82,  80,  54],
       [ 51,  79,  91,  69,  90],
       [ 97,  89,  91,  57,  84],
       [ 62,  93,  58,  96,  50],
       [ 89,  80,  67,  94,  50],
       [ 51,  92,  85,  80,  77],
       [ 92,  54,  92,  72,  95],
       [ 84,  58,  52,  61,  64],
       [ 70,  72, 100,  57,  98],
       [ 61,  54,  95,  90,  64],
       [ 84,  93,  84,  72,  73],
       [ 56,  52,  90,  96,  89],
       [ 50,  74,  91,  50,  64],
       [ 89,  95,  59,  75,  60],
       [ 60,  52,  95,  65,  93],
       [ 79,  99,  96,  64,  50],
       [ 96,  54,  86,  59,  89],
       [ 61,  68,  72,  90,  87],
       [ 78,  95,  51,  82, 100],
       [ 86,  69,  66,  63,  81],
       [ 51,  60,  62,  69,  78],
       [ 85,  81,  68,  53,  74],
       [ 59,  69,  88,  64,  61],
       [ 72,  75,  55,  78,  66],
       [ 87,  

In [4]:
#第一位學生分數
scores[0] #使用索引(index) (5,) --> size
scores[0,:] #使用slice (5,)
scores[0:1,:] #(1,5)

array([[71, 68, 56, 78, 89]], dtype=int32)

In [5]:
#前5位
scores[:5]

#前5位,前三科分數
scores[:5,:3]

array([[ 71,  68,  56],
       [ 67,  77,  52],
       [ 57,  65, 100],
       [ 87,  50,  96],
       [ 73,  55,  99]], dtype=int32)

In [6]:
#第1科
scores[:,0]

array([71, 67, 57, 87, 73, 93, 51, 97, 62, 89, 51, 92, 84, 70, 61, 84, 56,
       50, 89, 60, 79, 96, 61, 78, 86, 51, 85, 59, 72, 87, 89, 50, 93, 84,
       62, 70, 62, 57, 62, 50, 55, 70, 69, 86, 86, 95, 88, 50, 97, 96],
      dtype=int32)

In [7]:
#ndarray可以陣列運算
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4]
total

array([362, 340, 369, 371, 383, 385, 380, 418, 359, 380, 385, 405, 319,
       397, 364, 406, 383, 329, 378, 365, 388, 384, 378, 406, 365, 320,
       361, 341, 346, 449, 423, 352, 410, 369, 340, 381, 382, 414, 346,
       363, 390, 345, 333, 389, 333, 459, 396, 302, 342, 389], dtype=int32)

In [8]:
total/5

array([72.4, 68. , 73.8, 74.2, 76.6, 77. , 76. , 83.6, 71.8, 76. , 77. ,
       81. , 63.8, 79.4, 72.8, 81.2, 76.6, 65.8, 75.6, 73. , 77.6, 76.8,
       75.6, 81.2, 73. , 64. , 72.2, 68.2, 69.2, 89.8, 84.6, 70.4, 82. ,
       73.8, 68. , 76.2, 76.4, 82.8, 69.2, 72.6, 78. , 69. , 66.6, 77.8,
       66.6, 91.8, 79.2, 60.4, 68.4, 77.8])

In [9]:
#np內的function
np.sum(scores,axis=1) #加總(橫軸)
np.mean(scores,axis=1) #平均

#實體方法
scores.sum(axis=1)
scores.mean(axis=1)

array([72.4, 68. , 73.8, 74.2, 76.6, 77. , 76. , 83.6, 71.8, 76. , 77. ,
       81. , 63.8, 79.4, 72.8, 81.2, 76.6, 65.8, 75.6, 73. , 77.6, 76.8,
       75.6, 81.2, 73. , 64. , 72.2, 68.2, 69.2, 89.8, 84.6, 70.4, 82. ,
       73.8, 68. , 76.2, 76.4, 82.8, 69.2, 72.6, 78. , 69. , 66.6, 77.8,
       66.6, 91.8, 79.2, 60.4, 68.4, 77.8])